{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "piggydb.serviceAccountName" . }}
  labels:
{{ include "piggydb.labels" . | nindent 4 }}
{{- end -}}
